/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.realexpayments.hpp.sdk.RealexHpp;
import com.realexpayments.hpp.sdk.domain.HppRequest;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public String realexJson(){
		HppRequest hppRequest = new HppRequest()
								.addAmount(100)
								.addCurrency("EUR")
								.addMerchantId("eloquentix");

		RealexHpp realexHpp = new RealexHpp("secret");
	    return realexHpp.requestToJson(hppRequest);
    }

    public static void main(String[] args) {
        System.out.println(new App().realexJson());
    }
}
